version: '2'

services:
  dck_redis:
      #restart: always
    image: redis:latest
    command:
    - --loglevel warning
    volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis:Z

  dck_postgre:
      #restart: always
    # gitlab-ce's gitlab-rake backup (pg_dump) only suports 9.6-1
    image: sameersbn/postgresql:9.6-1
    #ports:
    #- "5432:5432"
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    # tunnel volume to pass postgresql bins to dck_gitlab
    #- tunnel_bin:/usr/bin
    #- tunnel_share:/usr/share
    environment:
    - DB_USER=gitlab_uas
    - DB_PASS=P@ssw0rd
    - DB_NAME=gitlab_buaauas_production
    - DB_EXTENSION=pg_trgm

  dck_gitlab:
    #restart: always
    #image: sameersbn/gitlab:8.16.6
    # updated psql and pg_dump command so gitlab-ce:8.17 can create backup of external postgresql of ver 9.6+
    #image: localhost:5000/lewis/gitlab-ce:8.17-psql_updated
    # updated cron utility for creating backup automatically at night
    image: localhost:5000/lewis/gitlab-ce:8.17_cron_updated
    depends_on:
    - dck_redis
    - dck_postgre
    ports:
    - "80:80"
    - "10022:22"
    - "443:443"
    volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data:Z
    - /srv/docker/gitlab/config:/etc/gitlab
    - /srv/docker/gitlab/postgresql/backups:/var/opt/gitlab/backups
    # folder external_backups used to store backups of external postgre database
    #- /srv/docker/gitlab/postgresql/backups:/var/opt/gitlab/external_backups
    # tunnel volume to receive bins from dck_postgre
    #- tunnel_bin:/var/opt/gitlab/postgre_usr/bin
    #- tunnel_share:/var/opt/gitlab/postgre_usr/share
    environment:
    - DEBUG=true

    - DB_ADAPTER=postgresql
    - DB_HOST=dck_postgre
    - DB_PORT=5432
    - DB_USER=gitlab_uas
    - DB_PASS=P@ssw0rd
    - DB_NAME=gitlab_buaauas_production
    - DB_EXTENSION=pg_trgm

    - REDIS_HOST=dck_redis
    - REDIS_PORT=6379

    - TZ=Asia/Beijing
    - GITLAB_TIMEZONE=Beijing

    - GITLAB_HTTPS=true
    - SSL_SELF_SIGNED=true

    - GITLAB_HOST=gitlab.melchior.vultr.com
    - GITLAB_PORT=80
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
    - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
    - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string

    - GITLAB_ROOT_PASSWORD=
    - GITLAB_ROOT_EMAIL=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=gitlabbuaauas@gmail.com
    - GITLAB_EMAIL_REPLY_TO=gitlabbuaauas@gmail.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=gitlabbuaauas@gmail.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=true
    - SMTP_DOMAIN=gmail.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=gitlabbuaauasa@gmail.com
    - SMTP_PASS=Bu@@u@s@g00gl3
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false

    - OAUTH_ENABLED=false
    - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
    - OAUTH_ALLOW_SSO=
    - OAUTH_BLOCK_AUTO_CREATED_USERS=true
    - OAUTH_AUTO_LINK_LDAP_USER=false
    - OAUTH_AUTO_LINK_SAML_USER=false
    - OAUTH_EXTERNAL_PROVIDERS=

    - OAUTH_CAS3_LABEL=cas3
    - OAUTH_CAS3_SERVER=
    - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
    - OAUTH_CAS3_LOGIN_URL=/cas/login
    - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
    - OAUTH_CAS3_LOGOUT_URL=/cas/logout

    - OAUTH_GOOGLE_API_KEY=
    - OAUTH_GOOGLE_APP_SECRET=
    - OAUTH_GOOGLE_RESTRICT_DOMAIN=

    - OAUTH_FACEBOOK_API_KEY=
    - OAUTH_FACEBOOK_APP_SECRET=

    - OAUTH_TWITTER_API_KEY=
    - OAUTH_TWITTER_APP_SECRET=

    - OAUTH_GITHUB_API_KEY=
    - OAUTH_GITHUB_APP_SECRET=
    - OAUTH_GITHUB_URL=
    - OAUTH_GITHUB_VERIFY_SSL=

    - OAUTH_GITLAB_API_KEY=
    - OAUTH_GITLAB_APP_SECRET=

    - OAUTH_BITBUCKET_API_KEY=
    - OAUTH_BITBUCKET_APP_SECRET=

    - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
    - OAUTH_SAML_IDP_CERT_FINGERPRINT=
    - OAUTH_SAML_IDP_SSO_TARGET_URL=
    - OAUTH_SAML_ISSUER=
    - OAUTH_SAML_LABEL="Our SAML Provider"
    - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
    - OAUTH_SAML_GROUPS_ATTRIBUTE=
    - OAUTH_SAML_EXTERNAL_GROUPS=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

    - OAUTH_CROWD_SERVER_URL=
    - OAUTH_CROWD_APP_NAME=
    - OAUTH_CROWD_APP_PASSWORD=

    - OAUTH_AUTH0_CLIENT_ID=
    - OAUTH_AUTH0_CLIENT_SECRET=
    - OAUTH_AUTH0_DOMAIN=

    - OAUTH_AZURE_API_KEY=
    - OAUTH_AZURE_API_SECRET=
    - OAUTH_AZURE_TENANT_ID=
# Create a tunnel to pass data between two containers
#volumes:
#    tunnel_bin: {}
#    tunnel_share: {}



